# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_shell_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='conf_file_update_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u914d\u7f6e\u6587\u4ef6\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
