# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0004_auto_20180313_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='config_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9879\u76ee\u914d\u7f6e\u6587\u4ef6'),
        ),
    ]
